# Generated by Django 5.1.1 on 2024-09-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='Gallery')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('age', models.CharField(choices=[('U13', 'Under 13'), ('U15', 'Under 15'), ('U17', 'Under 17')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], max_length=20)),
                ('email', models.EmailField(default='No Email Provided', max_length=254)),
                ('joinclub', models.TextField()),
                ('foreign', models.CharField(default='No Foreign Club Is Provided', max_length=100)),
                ('localclub', models.CharField(max_length=100)),
                ('academy', models.CharField(max_length=3, null=True)),
                ('oldClub', models.CharField(blank=True, max_length=100, null=True)),
                ('secondaryPosition', models.CharField(max_length=20)),
                ('thirdPosition', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=1)),
                ('preferredFoot', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('topPlayer', models.BooleanField(default=False)),
                ('src', models.ImageField(default='default_image.jpg', upload_to='Player/')),
                ('image_2', models.ImageField(default='default_image.jpg', upload_to='Player/')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('src', models.ImageField(upload_to='Shop')),
                ('href', models.CharField(max_length=20)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('src', models.ImageField(upload_to='Staff')),
                ('position', models.CharField(max_length=20)),
                ('qualification', models.TextField()),
                ('career', models.TextField()),
                ('facebookLink', models.CharField(max_length=50)),
                ('instagramLink', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], max_length=20)),
                ('src', models.ImageField(upload_to='FormerPlayer')),
                ('article', models.TextField(blank=True, null=True)),
                ('startYear', models.DateField()),
                ('endYear', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
    ]
