# Generated by Django 5.1.1 on 2024-09-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shop_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='tel',
            new_name='phone',
        ),
    ]
