# Generated by Django 5.1.1 on 2024-09-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sponser'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
