# Generated by Django 5.1.1 on 2024-09-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_player_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='localclub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
