# Generated by Django 5.1.1 on 2024-09-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_player_localclub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
    ]
