# Generated by Django 5.1.1 on 2024-09-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_player_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('src', models.ImageField(upload_to='News')),
                ('description', models.TextField()),
            ],
        ),
    ]
