# Generated by Django 5.1.1 on 2024-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_player_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='secondaryPosition',
            field=models.CharField(choices=[('GK', 'GK'), ('CB', 'CB'), ('LB', 'LB'), ('RB', 'RB'), ('DM', 'DM'), ('CM', 'CM'), ('AM', 'AM'), ('LW', 'LW'), ('ST', 'ST'), ('RW', 'RW')], max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='thirdPosition',
            field=models.CharField(choices=[('GK', 'GK'), ('CB', 'CB'), ('LB', 'LB'), ('RB', 'RB'), ('DM', 'DM'), ('CM', 'CM'), ('AM', 'AM'), ('LW', 'LW'), ('ST', 'ST'), ('RW', 'RW')], max_length=2),
        ),
    ]
